development:
  adapter: postgresql
  encoding: unicode
  database: cattle_log_dev
  host: localhost
  pool: 5


test: 
  adapter: postgresql
  encoding: utf8
  database: cattle_log_test
  host: localhost
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: cattle_log_prod
  pool: 5

