default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  encoding: unicode

development:
  database: cattlelog_dev
  <<: *default

production:
  database: cattlelog_prod
  <<: *default

test:
  database: cattlelog_test
  <<: *default